In [1]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in C:\Users\user\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in C:\Users\user\anaconda3\Lib\site-packages (2.4.6)
Requirement already satisfied: openpyxl in C:\Users\user\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in C:\Users\user\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: pymysql in C:\Users\user\anaconda3\Lib\site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\user\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et_xmlfile in C:\Users\user\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in C:\Users\user\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\user\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\user\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
# Import Required Libraries
import pandas as pd
import numpy as np

In [7]:
import os
print(os.getlogin())

user

In [9]:
import os

print(os.path.expanduser('~'))

C:\Users\user

In [10]:
import os

for root, dirs, files in os.walk(r'C:\Users\user'):
    if 'Ecommerce_Unclean_Project.xlsx' in files:
        print(os.path.join(root, 'Ecommerce_Unclean_Project.xlsx'))

C:\Users\user\Desktop\End to End Project\Ecommerce_Unclean_Project.xlsx

In [11]:
df = pd.read_excel(r'C:\Users\user\Desktop\End to End Project\Ecommerce_Unclean_Project.xlsx')

In [12]:
# Explore the Dataset
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [13]:
#View Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 107.3+ KB

In [14]:
#Statistical summary
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [15]:
#Dataset Shape
df.shape

(524, 15)

In [16]:
# Check Missing Values
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [17]:
#Check Duplicate Values
df.duplicated().sum()

np.int64(11)

In [18]:
#Remove Duplicate Records
df.drop_duplicates(inplace=True)

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
#Replace invalid values
df.replace(['N/A', '', 'NULL'],np.nan,inplace=True)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [21]:
#Remove Extra Spaces
df = df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

In [22]:
#Standardised text format
#Convert text into proper case

df['Customer_Name'] = df['Customer_Name'].str.title()
df['City'] = df['City'].str.title()
df['State'] = df['State'].str.title()

In [23]:
#Validate Email Addresses
#Keep Only Valid Emails

df = df[df['Email'].str.contains('@',na=False)]

In [42]:
#Convert Date Columns
df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')
df['Delivery_Date']=pd.to_datetime(df['Delivery_Date'],errors='coerce')

In [43]:
print(pd.__version__)

3.0.3

In [44]:
df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    errors='coerce',
    dayfirst=True,
    format='mixed'
)

df['Delivery_Date'] = pd.to_datetime(
    df['Delivery_Date'],
    errors='coerce',
    dayfirst=True,
    format='mixed'
)

In [45]:
import pandas as pd
import numpy as np

In [46]:
df = pd.read_excel(r'C:\Users\user\Desktop\End to End Project\Ecommerce_Unclean_Project.xlsx')

In [47]:
# Convert Numeric Columns

cols = ['Qty', 'Unit_Price', 'Discount']

for c in cols:
    df[c] = pd.to_numeric(df[c], errors='coerce')

In [48]:
#Remove Invalid Quantities 
#Remove zero or negative values

df= df[df['Qty']>0]

In [49]:
#Fill missing values

df['Discount'] = df['Discount'].fillna(0)

df['Phone'] = df['Phone'].fillna('Unknown')

df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [50]:
df['Sales'] = df['Qty'] * df['Unit_Price']

In [51]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,03-07-2025,7996.0
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025,24995.0
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025,5997.0
5,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,18-02-2025,1497.0
6,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,28-03-2025,2998.0
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,16-04-2025,NaN
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,16-01-2025,2997.0
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025,2997.0

In [52]:
#Net Amount


df['Net_Amount'] = df['Sales'] - (df['Sales'] * df['Discount'] / 100)

In [53]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,03-07-2025,7996.0,7996.00
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025,24995.0,19996.00
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025,5997.0,5697.15
5,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60
6,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,28-03-2025,2998.0,2998.00
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,16-04-2025,NaN,NaN
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,16-01-2025,2997.0,2997.00
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025,2997.0,2847.15

In [54]:
# Profit (Ex 20% Profit)

df['Profit'] = df['Net_Amount'] * 0.20

In [55]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43
5,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52
6,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,28-03-2025,2998.0,2998.00,599.60
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,16-04-2025,NaN,NaN,NaN
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,16-01-2025,2997.0,2997.00,599.40
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025,2997.0,2847.15,569.43

In [56]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43
5,ORD1007,10-02-2025,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52
6,ORD1008,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,28-03-2025,2998.0,2998.00,599.60
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,16-04-2025,NaN,NaN,NaN
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,16-01-2025,2997.0,2997.00,599.40
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025,2997.0,2847.15,569.43

In [57]:
df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    errors='coerce',
    dayfirst=True
)

In [58]:
# Order Month

df['Month'] = df['Order_Date'].dt.month_name()

In [59]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20,June
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20,February
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43,May
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52,February
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,28-03-2025,2998.0,2998.00,599.60,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,16-04-2025,NaN,NaN,NaN,April
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,16-01-2025,2997.0,2997.00,599.40,January
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025,2997.0,2847.15,569.43,March

In [60]:
# Order Year

df["Year"] = df["Order_Date"].dt.year

In [61]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20,June,2025.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20,February,2025.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43,May,2025.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52,February,2025.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,28-03-2025,2998.0,2998.00,599.60,NaN,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,16-04-2025,NaN,NaN,NaN,April,2025.0
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,16-01-2025,2997.0,2997.00,599.40,January,2025.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,09-03-2025,2997.0,2847.15,569.43,March,2025.0

In [63]:
# Weekday

df['Weekday'] = df['Order_Date'].dt.day_name()

In [64]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,03-07-2025,7996.0,7996.00,1599.20,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,09-02-2025,24995.0,19996.00,3999.20,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,08-05-2025,5997.0,5697.15,1139.43,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,18-02-2025,1497.0,1197.60,239.52,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,...,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025.0,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,UP,Mouse,Electronics,4.0,...,0.0,Card,Returned,27-02-2025,39996.0,39996.00,7999.20,February,2025.0,Monday
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,...,0.0,Wallet,Pending,28-03-2025,2998.0,2998.00,599.60,NaN,NaN,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,...,0.0,NetBanking,Delivered,16-04-2025,NaN,NaN,NaN,April,2025.0,Thursday
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,16-01-2025,2997.0,2997.00,599.40,January,2025.0,Saturday
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,5.0,COD,Cancelled,09-03-2025,2997.0,2847.15,569.43,March,2025.0,Monday

In [65]:
#Final Data Validation

df.info()

<class 'pandas.DataFrame'>
Index: 402 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       402 non-null    str
 1   Order_Date     353 non-null    datetime64[us]
 2   Customer_Name  402 non-null    str
 3   Email          402 non-null    str
 4   Phone          402 non-null    object
 5   City           402 non-null    str
 6   State          402 non-null    str
 7   Product        402 non-null    str
 8   Category       402 non-null    str
 9   Qty            402 non-null    float64
 10  Unit_Price     363 non-null    float64
 11  Discount       402 non-null    float64
 12  Payment_Mode   402 non-null    str
 13  Order_Status   402 non-null    str
 14  Delivery_Date  402 non-null    str
 15  Sales          363 non-null    float64
 16  Net_Amount     363 non-null    float64
 17  Profit         363 non-null    float64
 18  Month          353 non-null    str
 19  Year           353 non-null    float64
 20  Weekday        353 non-null    str
dtypes: datetime64[us](1), float64(7), object(1), str(12)
memory usage: 105.3+ KB

In [66]:
# Check Missing Values

df.isnull().sum()

Order_ID          0
Order_Date       49
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       39
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     0
Sales            39
Net_Amount       39
Profit           39
Month            49
Year             49
Weekday          49
dtype: int64

In [67]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Sales,Net_Amount,Profit,Year
count,353,402.000000,363.000000,402.000000,363.000000,363.000000,363.000000,353.0
mean,2025-04-02 17:52:51.671388,3.320896,3251.341598,7.823383,11115.680441,10260.530579,2052.106116,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,499.000000,399.200000,79.840000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.000000,2599.000000,2398.400000,479.680000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,5.000000,5997.000000,5996.000000,1199.200000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,15.000000,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.460711,3034.218072,7.922703,12245.226283,11543.812960,2308.762592,0.0

In [68]:
# Step 16: Export Clean Data

df.to_csv('Clean_Ecommerce.csv', index=False)

In [71]:
# Step 17: Import Data into MySQL

from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:YOURPASSWORD@localhost/ecommerce')

In [72]:
# Export DataFrame to MySQL

df.to_sql(
    name='orders',
    con=engine,
    if_exists='replace',
    index=False
)

402

In [73]:
df.shape

(402, 21)